/*
 * ChannelEngine Channel API
 * ChannelEngine API for channels
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.channelengine.channel.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.channel.apiclient.model.ChannelCancellationLineResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChannelCancellationResponse
 */

public class ChannelCancellationResponse {
  @SerializedName("ChannelOrderNo")
  private String channelOrderNo = null;

  @SerializedName("Lines")
  private List<ChannelCancellationLineResponse> lines = new ArrayList<ChannelCancellationLineResponse>();

  @SerializedName("Reason")
  private String reason = null;

  /**
   * Reason code for cancellation
   */
  @JsonAdapter(ReasonCodeEnum.Adapter.class)
  public enum ReasonCodeEnum {
    NOT_IN_STOCK("NOT_IN_STOCK"),
    
    DAMAGED("DAMAGED"),
    
    INCOMPLETE("INCOMPLETE"),
    
    CLIENT_CANCELLED("CLIENT_CANCELLED"),
    
    INVALID_ADDRESS("INVALID_ADDRESS"),
    
    OTHER("OTHER");

    private String value;

    ReasonCodeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReasonCodeEnum fromValue(String text) {
      for (ReasonCodeEnum b : ReasonCodeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ReasonCodeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReasonCodeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReasonCodeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ReasonCodeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("ReasonCode")
  private ReasonCodeEnum reasonCode = null;

  public ChannelCancellationResponse channelOrderNo(String channelOrderNo) {
    this.channelOrderNo = channelOrderNo;
    return this;
  }

   /**
   * The unique order reference used by the Channel
   * @return channelOrderNo
  **/
  @ApiModelProperty(required = true, value = "The unique order reference used by the Channel")
  public String getChannelOrderNo() {
    return channelOrderNo;
  }

  public void setChannelOrderNo(String channelOrderNo) {
    this.channelOrderNo = channelOrderNo;
  }

  public ChannelCancellationResponse lines(List<ChannelCancellationLineResponse> lines) {
    this.lines = lines;
    return this;
  }

  public ChannelCancellationResponse addLinesItem(ChannelCancellationLineResponse linesItem) {
    this.lines.add(linesItem);
    return this;
  }

   /**
   * Get lines
   * @return lines
  **/
  @ApiModelProperty(required = true, value = "")
  public List<ChannelCancellationLineResponse> getLines() {
    return lines;
  }

  public void setLines(List<ChannelCancellationLineResponse> lines) {
    this.lines = lines;
  }

  public ChannelCancellationResponse reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason for cancellation (text)
   * @return reason
  **/
  @ApiModelProperty(value = "Reason for cancellation (text)")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public ChannelCancellationResponse reasonCode(ReasonCodeEnum reasonCode) {
    this.reasonCode = reasonCode;
    return this;
  }

   /**
   * Reason code for cancellation
   * @return reasonCode
  **/
  @ApiModelProperty(value = "Reason code for cancellation")
  public ReasonCodeEnum getReasonCode() {
    return reasonCode;
  }

  public void setReasonCode(ReasonCodeEnum reasonCode) {
    this.reasonCode = reasonCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelCancellationResponse channelCancellationResponse = (ChannelCancellationResponse) o;
    return Objects.equals(this.channelOrderNo, channelCancellationResponse.channelOrderNo) &&
        Objects.equals(this.lines, channelCancellationResponse.lines) &&
        Objects.equals(this.reason, channelCancellationResponse.reason) &&
        Objects.equals(this.reasonCode, channelCancellationResponse.reasonCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelOrderNo, lines, reason, reasonCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelCancellationResponse {\n");
    
    sb.append("    channelOrderNo: ").append(toIndentedString(channelOrderNo)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

