/*
 * ChannelEngine Channel API
 * ChannelEngine API for channels
 *
 * The version of the OpenAPI document: 2.9.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.channelengine.channel.apiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.channelengine.channel.apiclient.model.ChannelProductResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChannelProductChangesResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ChannelProductChangesResponse {
  public static final String SERIALIZED_NAME_TO_BE_CREATED = "ToBeCreated";
  @SerializedName(SERIALIZED_NAME_TO_BE_CREATED)
  private List<ChannelProductResponse> toBeCreated = null;

  public static final String SERIALIZED_NAME_TO_BE_UPDATED = "ToBeUpdated";
  @SerializedName(SERIALIZED_NAME_TO_BE_UPDATED)
  private List<ChannelProductResponse> toBeUpdated = null;

  public static final String SERIALIZED_NAME_TO_BE_REMOVED = "ToBeRemoved";
  @SerializedName(SERIALIZED_NAME_TO_BE_REMOVED)
  private List<String> toBeRemoved = null;


  public ChannelProductChangesResponse toBeCreated(List<ChannelProductResponse> toBeCreated) {
    
    this.toBeCreated = toBeCreated;
    return this;
  }

  public ChannelProductChangesResponse addToBeCreatedItem(ChannelProductResponse toBeCreatedItem) {
    if (this.toBeCreated == null) {
      this.toBeCreated = new ArrayList<ChannelProductResponse>();
    }
    this.toBeCreated.add(toBeCreatedItem);
    return this;
  }

   /**
   * Get toBeCreated
   * @return toBeCreated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ChannelProductResponse> getToBeCreated() {
    return toBeCreated;
  }


  public void setToBeCreated(List<ChannelProductResponse> toBeCreated) {
    this.toBeCreated = toBeCreated;
  }


  public ChannelProductChangesResponse toBeUpdated(List<ChannelProductResponse> toBeUpdated) {
    
    this.toBeUpdated = toBeUpdated;
    return this;
  }

  public ChannelProductChangesResponse addToBeUpdatedItem(ChannelProductResponse toBeUpdatedItem) {
    if (this.toBeUpdated == null) {
      this.toBeUpdated = new ArrayList<ChannelProductResponse>();
    }
    this.toBeUpdated.add(toBeUpdatedItem);
    return this;
  }

   /**
   * Get toBeUpdated
   * @return toBeUpdated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ChannelProductResponse> getToBeUpdated() {
    return toBeUpdated;
  }


  public void setToBeUpdated(List<ChannelProductResponse> toBeUpdated) {
    this.toBeUpdated = toBeUpdated;
  }


  public ChannelProductChangesResponse toBeRemoved(List<String> toBeRemoved) {
    
    this.toBeRemoved = toBeRemoved;
    return this;
  }

  public ChannelProductChangesResponse addToBeRemovedItem(String toBeRemovedItem) {
    if (this.toBeRemoved == null) {
      this.toBeRemoved = new ArrayList<String>();
    }
    this.toBeRemoved.add(toBeRemovedItem);
    return this;
  }

   /**
   * Get toBeRemoved
   * @return toBeRemoved
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getToBeRemoved() {
    return toBeRemoved;
  }


  public void setToBeRemoved(List<String> toBeRemoved) {
    this.toBeRemoved = toBeRemoved;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelProductChangesResponse channelProductChangesResponse = (ChannelProductChangesResponse) o;
    return Objects.equals(this.toBeCreated, channelProductChangesResponse.toBeCreated) &&
        Objects.equals(this.toBeUpdated, channelProductChangesResponse.toBeUpdated) &&
        Objects.equals(this.toBeRemoved, channelProductChangesResponse.toBeRemoved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toBeCreated, toBeUpdated, toBeRemoved);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelProductChangesResponse {\n");
    sb.append("    toBeCreated: ").append(toIndentedString(toBeCreated)).append("\n");
    sb.append("    toBeUpdated: ").append(toIndentedString(toBeUpdated)).append("\n");
    sb.append("    toBeRemoved: ").append(toIndentedString(toBeRemoved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

